# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controller.UserControler import UserController
from mainmenu import Ui_MainWindow

class Ui_Login(object):
    def __init__(self):
        self.login_controller = UserController(self)
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(636, 432)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        Login.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../icons/bx-log-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        self.emailLineEdit = QtWidgets.QLineEdit(Login)
        self.emailLineEdit.setGeometry(QtCore.QRect(130, 110, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setStyleSheet("border : 1px solid rgb(85, 170, 255);\n"
"border-radius :4px;")
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.label = QtWidgets.QLabel(Login)
        self.label.setGeometry(QtCore.QRect(230, 370, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:  rgb(85, 170, 255);\n"
"")
        self.label.setObjectName("label")
        self.btnValider = QtWidgets.QPushButton(Login)
        self.btnValider.setGeometry(QtCore.QRect(370, 290, 151, 41))
        self.btnValider.setObjectName("btnValider")
        self.remember = QtWidgets.QCheckBox(Login)
        self.remember.setGeometry(QtCore.QRect(130, 300, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.remember.setFont(font)
        self.remember.setObjectName("remember")
        self.connexionLabel = QtWidgets.QLabel(Login)
        self.connexionLabel.setGeometry(QtCore.QRect(160, 30, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.connexionLabel.setFont(font)
        self.connexionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connexionLabel.setObjectName("connexionLabel")
        self.passwordLineEdit = QtWidgets.QLineEdit(Login)
        self.passwordLineEdit.setGeometry(QtCore.QRect(130, 210, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("border : 1px solid rgb(85, 170, 255);\n"
"border-radius :4px;")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.label_3 = QtWidgets.QLabel(Login)
        self.label_3.setGeometry(QtCore.QRect(90, 220, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\icons/bx-lock.svg"))
        self.label_3.setObjectName("label_3")
        self.user_icon = QtWidgets.QLabel(Login)
        self.user_icon.setGeometry(QtCore.QRect(90, 110, 31, 41))
        self.user_icon.setText("")
        self.user_icon.setTextFormat(QtCore.Qt.PlainText)
        self.user_icon.setPixmap(QtGui.QPixmap(".\\icons/bx-user.svg"))
        self.user_icon.setObjectName("user_icon")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        
        #--------------------Evennements--------------------------------------
        self.x = self.btnValider.clicked.connect(lambda:self.login_controller.login(self.emailLineEdit.text(),self.passwordLineEdit.text(),Ui_MainWindow,Login))

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Connexion"))
        self.emailLineEdit.setPlaceholderText(_translate("Login", "Nom utilisateur"))
        self.label.setText(_translate("Login", "Mot de passe oublié ?"))
        self.btnValider.setText(_translate("Login", "LOGIN"))
        self.remember.setText(_translate("Login", "Se souvenir"))
        self.connexionLabel.setText(_translate("Login", "CONNNEXION"))
        self.passwordLineEdit.setPlaceholderText(_translate("Login", "Mot de passe"))
import sys

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogIn = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(LogIn)
    LogIn.show()
    sys.exit(app.exec_())