# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainlogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from controller.UserControler import UserController
from mainmenu import Ui_MainWindow


class Ui_Login(object):
    def __init__(self):
        self.login_controller = UserController(self)        
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(714, 539)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.passwordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(170, 240, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("border : 1px solid rgb(85, 170, 255);\n"
"border-radius :4px;")
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.remember = QtWidgets.QCheckBox(self.centralwidget)
        self.remember.setGeometry(QtCore.QRect(170, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.remember.setFont(font)
        self.remember.setObjectName("remember")
        self.user_icon = QtWidgets.QLabel(self.centralwidget)
        self.user_icon.setGeometry(QtCore.QRect(130, 140, 31, 41))
        self.user_icon.setText("")
        self.user_icon.setTextFormat(QtCore.Qt.PlainText)
        self.user_icon.setPixmap(QtGui.QPixmap(".\\icons/bx-user.svg"))
        self.user_icon.setObjectName("user_icon")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 400, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:  rgb(85, 170, 255);\n"
"")
        self.label.setObjectName("label")
        self.connexionLabel = QtWidgets.QLabel(self.centralwidget)
        self.connexionLabel.setGeometry(QtCore.QRect(200, 60, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.connexionLabel.setFont(font)
        self.connexionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connexionLabel.setObjectName("connexionLabel")
        self.emailLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.emailLineEdit.setGeometry(QtCore.QRect(170, 140, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setStyleSheet("border : 1px solid rgb(85, 170, 255);\n"
"border-radius :4px;")
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 240, 31, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\icons/bx-lock.svg"))
        self.label_3.setObjectName("label_3")
        self.btnValider = QtWidgets.QPushButton(self.centralwidget)
        self.btnValider.setGeometry(QtCore.QRect(410, 320, 151, 41))
        self.btnValider.setObjectName("btnValider")
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 26))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        
        #--------------------Evennements--------------------------------------
        self.x = self.btnValider.clicked.connect(lambda:self.login_controller.login(self.emailLineEdit.text(),self.passwordLineEdit.text(),Ui_Login,Login))

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.passwordLineEdit.setPlaceholderText(_translate("Login", "Mot de passe"))
        self.remember.setText(_translate("Login", "Se souvenir"))
        self.label.setText(_translate("Login", "Mot de passe oublié ?"))
        self.connexionLabel.setText(_translate("Login", "CONNNEXION"))
        self.emailLineEdit.setPlaceholderText(_translate("Login", "Nom utilisateur"))
        self.btnValider.setText(_translate("Login", "LOGIN"))
import sys

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogIn = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(LogIn)
    LogIn.show()
    sys.exit(app.exec_())